name: RodBot

on:
  issue_comment: {}

jobs:
  rodbot:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          mkdir -p "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          curl -sSL https://github.com/ctron/rodbot/releases/download/v0.1.1/rodbot-linux-amd64 -o "$HOME/.local/bin/rodbot"
          chmod a+x "$HOME/.local/bin/rodbot"
      - run: rodbot