name: RodBot

on:
  issue_comment: {}

jobs:
  rodbot:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sudo curl -sSL https://github.com/ctron/rodbot/releases/download/v0.1.1/rodbot-linux-amd64 -o /usr/bin/rodbot
          sudo chmod a+x /usr/bin/rodbot
      - run: rodbot