name: RodBot

on:
  issue_comment: {}

jobs:
  rodbot:
    runs-on: ubuntu-20.04

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ctron/rodbot-action@v0.1.0
